export const careerCategories = [
  { id: 1, name: 'Career & Jobs', icon: '💼', color: '#3b82f6', description: 'Job opportunities, roles, and career paths after BSc IT' },
  { id: 2, name: 'Higher Studies', icon: '🎓', color: '#8b5cf6', description: 'MCA, MBA, MSc, certifications and further education' },
  { id: 3, name: 'Skills & Learning', icon: '📚', color: '#22c55e', description: 'Technical skills, projects, and self-improvement' },
  { id: 4, name: 'Salary & Future', icon: '💰', color: '#f59e0b', description: 'Salary expectations, growth, and industry trends' },
  { id: 5, name: 'Freelancing & Business', icon: '🚀', color: '#ef4444', description: 'Freelancing, startups, and online income' },
  { id: 6, name: 'Interview & Resume', icon: '📋', color: '#ec4899', description: 'Interview prep, resume tips, and job search' },
  { id: 7, name: 'Confusion & Motivation', icon: '💪', color: '#14b8a6', description: 'Overcoming doubts, staying motivated, and making decisions' },
]

export const careerQuestions = [
  { category_id: 1, question: 'What jobs can I get after BSc IT?' },
  { category_id: 1, question: 'Is BSc IT enough to get a software developer job?' },
  { category_id: 1, question: 'Which IT job has the highest salary for freshers?' },
  { category_id: 1, question: 'Can I get a government job after BSc IT?' },
  { category_id: 1, question: 'What are the best private jobs after BSc IT?' },
  { category_id: 1, question: 'Can I work in cybersecurity after BSc IT?' },
  { category_id: 1, question: 'How do I become a data analyst after BSc IT?' },
  { category_id: 1, question: 'Can BSc IT students become software engineers?' },
  { category_id: 1, question: 'What is the salary of a BSc IT fresher in India?' },
  { category_id: 1, question: 'Which companies hire BSc IT freshers?' },
  { category_id: 1, question: 'How can I get an internship after BSc IT?' },
  { category_id: 1, question: 'What skills are required for IT jobs?' },
  { category_id: 1, question: 'Can I get a remote job after BSc IT?' },
  { category_id: 1, question: 'Is coding mandatory after BSc IT?' },
  { category_id: 1, question: 'What are the easiest IT jobs for freshers?' },
  { category_id: 1, question: 'Can I work abroad after BSc IT?' },
  { category_id: 1, question: 'How do I prepare for IT interviews?' },
  { category_id: 1, question: 'What are the top career options after BSc IT?' },
  { category_id: 1, question: 'Which programming language should I learn first?' },
  { category_id: 1, question: 'Can I become a web developer after BSc IT?' },

  { category_id: 2, question: 'Should I do MCA after BSc IT?' },
  { category_id: 2, question: 'Is MBA better than MCA after BSc IT?' },
  { category_id: 2, question: 'What are the best courses after BSc IT?' },
  { category_id: 2, question: 'Can I do MSc IT after BSc IT?' },
  { category_id: 2, question: 'Which certification is best after BSc IT?' },
  { category_id: 2, question: 'Should I prepare for GATE after BSc IT?' },
  { category_id: 2, question: 'Can I study abroad after BSc IT?' },
  { category_id: 2, question: 'What is the best master degree after BSc IT?' },
  { category_id: 2, question: 'Can BSc IT students do AI and Machine Learning?' },
  { category_id: 2, question: 'Which online courses are best for BSc IT students?' },
  { category_id: 2, question: 'Is cloud computing a good career after BSc IT?' },
  { category_id: 2, question: 'Can I switch to management after BSc IT?' },
  { category_id: 2, question: 'Should I do a diploma after BSc IT?' },
  { category_id: 2, question: 'How useful are Google certifications after BSc IT?' },
  { category_id: 2, question: 'Can I pursue digital marketing after BSc IT?' },

  { category_id: 3, question: 'Which technical skills should I learn after BSc IT?' },
  { category_id: 3, question: 'How can I improve my coding skills?' },
  { category_id: 3, question: 'What projects should BSc IT students build?' },
  { category_id: 3, question: 'How can I create a strong resume after BSc IT?' },
  { category_id: 3, question: 'What are the best free websites to learn coding?' },
  { category_id: 3, question: 'How can I learn full stack development?' },
  { category_id: 3, question: 'Which IT certifications are most valuable?' },
  { category_id: 3, question: 'How do I start freelancing after BSc IT?' },
  { category_id: 3, question: 'Can I learn AI without strong mathematics?' },
  { category_id: 3, question: 'What are the best GitHub projects for beginners?' },
  { category_id: 3, question: 'How do I become job ready after BSc IT?' },
  { category_id: 3, question: 'Which soft skills are important for IT jobs?' },
  { category_id: 3, question: 'How can I improve communication skills for interviews?' },
  { category_id: 3, question: 'Should I learn DSA after BSc IT?' },
  { category_id: 3, question: 'How can I build a portfolio website?' },

  { category_id: 4, question: 'What is the future scope of BSc IT?' },
  { category_id: 4, question: 'Is BSc IT better than BCA?' },
  { category_id: 4, question: 'Can BSc IT students earn 1 lakh per month?' },
  { category_id: 4, question: 'Which IT field is best for the future?' },
  { category_id: 4, question: 'What are the highest paying skills in IT?' },
  { category_id: 4, question: 'Can I become rich after BSc IT?' },
  { category_id: 4, question: 'How fast can I grow my salary in IT?' },
  { category_id: 4, question: 'What are the top paying countries for IT jobs?' },
  { category_id: 4, question: 'Will AI replace IT jobs?' },
  { category_id: 4, question: 'Which IT careers are safe from automation?' },

  { category_id: 5, question: 'Can I start freelancing after BSc IT?' },
  { category_id: 5, question: 'How do I get freelance clients as a beginner?' },
  { category_id: 5, question: 'Which freelancing skills pay the most?' },
  { category_id: 5, question: 'Can I start a startup after BSc IT?' },
  { category_id: 5, question: 'How do I earn online after BSc IT?' },
  { category_id: 5, question: 'Can I become a YouTuber or tech blogger after BSc IT?' },
  { category_id: 5, question: 'How can I start a web development business?' },
  { category_id: 5, question: 'What are the best side hustles for IT students?' },
  { category_id: 5, question: 'Can I earn money from coding projects?' },
  { category_id: 5, question: 'How do I become a successful freelancer?' },

  { category_id: 6, question: 'What questions are asked in IT interviews?' },
  { category_id: 6, question: 'How should a BSc IT fresher resume look?' },
  { category_id: 6, question: 'How do I answer HR interview questions?' },
  { category_id: 6, question: 'What are the common coding interview questions?' },
  { category_id: 6, question: 'How can I crack TCS interview after BSc IT?' },
  { category_id: 6, question: 'How do I prepare for aptitude tests?' },
  { category_id: 6, question: 'What mistakes should freshers avoid in interviews?' },
  { category_id: 6, question: 'How important are internships in IT?' },
  { category_id: 6, question: 'How can I explain projects in interviews?' },
  { category_id: 6, question: 'What should I include in my LinkedIn profile?' },

  { category_id: 7, question: 'I completed BSc IT and feel confused, what should I do?' },
  { category_id: 7, question: 'What if I am weak in coding after BSc IT?' },
  { category_id: 7, question: 'Can an average student succeed in IT?' },
  { category_id: 7, question: 'How do I choose the right career path?' },
  { category_id: 7, question: 'What should I do if I don\'t get a job after graduation?' },
  { category_id: 7, question: 'How can I stay motivated during job search?' },
  { category_id: 7, question: 'Is it too late to start coding after graduation?' },
  { category_id: 7, question: 'Can I change my career after BSc IT?' },
  { category_id: 7, question: 'What are the biggest mistakes BSc IT students make?' },
  { category_id: 7, question: 'How do I avoid wasting time after graduation?' },
]
